class Challenge < ApplicationRecord
  belongs_to :journey

  validates :completed, inclusion: { in: [true, false] }

  FRONTEND = [
    "HTML Basics",
    "CSS Basics",
    "Understanding the Box Model",
    "Introduction to Flexbox",
    "Responsive Web Design Principles",
    "Introduction to JavaScript",
    "DOM Manipulation",
    "Basic Event Handling",
    "Introduction to CSS Grid",
    "CSS Selectors and Specificity",
    "Media Queries for Responsive Design",
    "CSS Transitions",
    "Introduction to Git and Version Control",
    "Basic Command Line Usage",
    "Introduction to Web Accessibility",
    "Introduction to JSON and API Basics",
    "Introduction to NPM (Node Package Manager)",
    "Introduction to Node.js",
    "Working with External Libraries (e.g., jQuery)",
    "Introduction to CSS Preprocessors (e.g., Sass)",
    "Introduction to Task Runners (e.g., Gulp, Grunt)",
    "Basic CSS Animations",
    "Introduction to Web Components",
    "Introduction to Vue.js or React Basics",
    "Responsive Images and Video",
    "CSS Flexbox and Grid Layout",
    "Advanced JavaScript Concepts (Closures, Promises)",
    "AJAX and Fetch API",
    "Introduction to TypeScript",
    "Building Single Page Applications (SPAs)",
    "State Management in Front-end Frameworks",
    "Advanced DOM Manipulation Techniques",
    "Working with Canvas for Graphics",
    "Web Performance Optimization Strategies",
    "Introduction to Progressive Web Apps (PWAs)",
    "Web Security Best Practices",
    "Introduction to GraphQL",
    "Introduction to WebSockets",
    "Cross-Browser Compatibility",
    "Responsive Typography",
    "Serverless Architecture for Front-end Developers",
    "Web Assembly (Wasm) Basics",
    "Working with RESTful APIs",
    "Introduction to Testing (Unit Testing)",
    "Client-Side Routing in SPAs",
    "Advanced CSS Layout Techniques",
    "Introduction to Web Workers",
    "Optimizing for Mobile Devices",
    "Creating and Using Design Systems",
    "Accessibility Beyond Basics",
    "Building Custom UI Components",
    "CSS-in-JS Approaches",
    "State Management Libraries (e.g., Redux)",
    "Advanced Webpack Configurations",
    "Building Progressive Web Apps (PWAs)",
    "Advanced React or Vue.js Concepts",
    "GraphQL for Front-end Developers",
    "Understanding and Implementing Design Patterns",
    "Mobile App Development with React Native or Flutter",
    "Optimizing for Performance in Large-Scale Applications"
  ]
  BACKEND = [
    "Introduction to Server-side Programming Languages (e.g., Node.js, Python, Ruby)",
    "RESTful API Design",
    "Understanding Web Servers (e.g., Apache, Nginx)",
    "Introduction to Database Systems (e.g., MySQL, PostgreSQL)",
    "Introduction to NoSQL Databases (e.g., MongoDB, Redis)",
    "SQL Basics",
    "Understanding ORM (Object-Relational Mapping) Concepts",
    "Authentication and Authorization Basics",
    "Introduction to Token-based Authentication (e.g., JWT)",
    "Session Management",
    "Middleware and Middleware Frameworks",
    "Introduction to Web Application Security",
    "SSL/TLS Encryption Basics",
    "Understanding Hashing Algorithms",
    "Introduction to Caching Strategies",
    "Message Queue Systems (e.g., RabbitMQ, Kafka)",
    "Introduction to Microservices Architecture",
    "Containerization Basics (e.g., Docker)",
    "Introduction to Container Orchestration (e.g., Kubernetes)",
    "Serverless Architecture Concepts",
    "Introduction to GraphQL",
    "Introduction to WebSockets for Real-time Communication",
    "Understanding HTTP/2 and HTTP/3 Protocols",
    "API Documentation Tools (e.g., Swagger, OpenAPI)",
    "GraphQL Schema Design Basics",
    "Background Jobs and Task Queues",
    "Version Control for Codebase Management (e.g., Git)",
    "Introduction to GitHub/GitLab Basics",
    "Command Line Basics",
    "Introduction to Responsive Images",
    "Introduction to CSS Frameworks (e.g., Bootstrap, Bulma)",
    "Introduction to CSS Preprocessors (e.g., Sass, Less)",
    "CSS Methodologies (e.g., BEM, SMACSS)",
    "Browser Developer Tools Basics",
    "Web Performance Tools (e.g., Lighthouse, PageSpeed Insights)",
    "Introduction to Web Animation Libraries (e.g., GreenSock)",
    "Introduction to React Basics",
    "Understanding React Components and Props",
    "Server-side Rendering (SSR) and Client-side Rendering (CSR)",
    "GraphQL Server Implementation",
    "Introduction to React State and Lifecycle",
    "Introduction to React Hooks",
    "Introduction to React Router",
    "Introduction to React Forms",
    "Introduction to Redux Basics",
    "Introduction to Vue.js Basics",
    "Understanding Vue Components and Props",
    "Introduction to Vue State Management",
    "Introduction to Vue Router",
    "Understanding Vue Directives",
    "Responsive Typography Basics",
    "Introduction to CSS Variables",
    "Introduction to CSS-in-JS",
    "Introduction to Responsive Tables",
    "Introduction to WebAssembly (Wasm)",
    "Introduction to GraphQL Basics",
    "API Documentation Fundamentals",
    "Advanced Database Concepts (e.g., Database Indexing, Transactions, Query Optimization)",
    "Introduction to Web Design Principles",
    "Introduction to CI/CD (Continuous Integration and Continuous Deployment)"
  ]
  DATA_SCIENCE = [
    "Statistical Analysis Basics",
    "Probability Theory Basics",
    "Introduction to Exploratory Data Analysis (EDA)",
    "Data Cleaning and Preprocessing Fundamentals",
    "Data Visualization Basics",
    "Descriptive Statistics Basics",
    "Inferential Statistics Basics",
    "Hypothesis Testing Basics",
    "Introduction to Linear Regression",
    "Introduction to Logistic Regression",
    "Introduction to Decision Trees",
    "Introduction to Gradient Boosting",
    "Introduction to Clustering Algorithms (e.g., K-Means, Hierarchical)",
    "Principal Component Analysis (PCA) Basics",
    "Feature Engineering Basics",
    "Feature Selection Basics",
    "Introduction to Time Series Analysis",
    "Introduction to ARIMA Models",
    "Introduction to Natural Language Processing (NLP)",
    "Introduction to Text Mining",
    "Introduction to Sentiment Analysis",
    "Machine Learning Pipelines Basics",
    "Introduction to Cross-Validation Techniques",
    "Introduction to Ensemble Learning",
    "Basics of Neural Networks",
    "Deep Learning Frameworks (e.g., TensorFlow, PyTorch) Basics",
    "Introduction to Reinforcement Learning",
    "Introduction to Association Rule Mining",
    "Introduction to Anomaly Detection",
    "Introduction to Dimensionality Reduction",
    "Introduction to Model Evaluation Metrics",
    "Understanding Bias and Fairness in Machine Learning",
    "Basics of Explainable AI",
    "Introduction to Big Data Technologies (e.g., Hadoop, Spark)",
    "Basics of Data Warehousing",
    "SQL for Data Science Basics",
    "Introduction to NoSQL Databases (e.g., MongoDB)",
    "Introduction to Web Scraping for Data Collection",
    "Introduction to APIs for Data Retrieval",
    "Basics of Data Ethics",
    "Introduction to A/B Testing",
    "Basics of Feature Scaling and Normalization",
    "Introduction to Regularization in Machine Learning",
    "Introduction to Hyperparameter Tuning",
    "Basics of Model Deployment Strategies",
    "Introduction to Docker for Data Science",
    "Basics of Data Governance",
    "Differences between Data Lakes and Data Warehouses",
    "Introduction to Geospatial Data Analysis",
    "Understanding Time Complexity and Space Complexity",
    "Optimal Algorithm Design Basics",
    "Introduction to Bayesian Statistics",
    "Introduction to Network Analysis",
    "Introduction to Deep Reinforcement Learning",
    "Basics of Optical Character Recognition (OCR)",
    "Introduction to Automated Machine Learning (AutoML)",
    "Introduction to Data Science in Cloud Platforms (e.g., AWS, Azure)",
    "Introduction to Graph Databases and Analysis",
    "Basics of Data Privacy and Security",
    "Understanding Bias-Variance Tradeoff"
  ]
  DATA_ANALYST = [
    "Data Exploration Basics",
    "Descriptive Statistics Basics",
    "Inferential Statistics Basics",
    "Probability Distributions Basics",
    "Statistical Hypothesis Testing Basics",
    "Correlation and Regression Analysis Basics",
    "Time Series Analysis Basics",
    "Data Cleaning and Preprocessing Fundamentals",
    "Data Visualization Basics",
    "Dashboard Creation Basics",
    "Excel for Data Analysis Basics",
    "SQL for Data Analysis Basics",
    "Python for Data Analysis (pandas, numpy) Basics",
    "R Programming for Data Analytics Basics",
    "Data Wrangling Techniques Basics",
    "Exploratory Data Analysis (EDA) Basics",
    "Feature Engineering Basics",
    "Data Sampling Techniques Basics",
    "A/B Testing Basics",
    "Predictive Modeling Basics",
    "Introduction to Machine Learning Algorithms",
    "Customer Segmentation Basics",
    "Cohort Analysis Basics",
    "Churn Analysis Basics",
    "Customer Lifetime Value (CLV) Basics",
    "Market Basket Analysis Basics",
    "RFM Analysis Basics",
    "Text Analytics Basics",
    "Sentiment Analysis Basics",
    "Social Media Analytics Basics",
    "Web Analytics Basics",
    "Data-driven Decision Making Basics",
    "KPI (Key Performance Indicator) Selection Basics",
    "Data Governance Basics",
    "Data Quality Management Basics",
    "Data Ethics Basics",
    "Big Data Technologies (e.g., Hadoop, Spark) Basics",
    "Predictive Maintenance Analytics Basics",
    "Supply Chain Analytics Basics",
    "Healthcare Analytics Basics",
    "Financial Analytics Basics",
    "Fraud Detection Analytics Basics",
    "Risk Analytics Basics",
    "Geospatial Analytics Basics",
    "Network Analytics Basics",
    "Decision Trees and Random Forests Basics",
    "Cluster Analysis Basics",
    "Association Rule Mining Basics",
    "Linear and Logistic Regression Basics",
    "Time Complexity and Space Complexity Basics",
    "Optimal Algorithm Design Basics",
    "Data Storytelling Basics",
    "Data Privacy and Security Basics",
    "Data Visualization Tools (e.g., Tableau, Power BI) Basics",
    "Data Warehousing Basics",
    "SQL Optimization Techniques Basics",
    "Data Fusion and Integration Basics",
    "Data Scraping Techniques Basics",
    "Data Mining Concepts Basics",
    "Machine Learning Model Interpretability Basics"
  ]
  MENTAL_HEALTH = [
    "Practice deep breathing exercises for 5 minutes.",
    "Write down your thoughts and feelings in a journal.",
    "Try a guided meditation",
    "Connect with a friend or family member for a meaningful conversation.",
    "Consider joining a yoga class for a holistic mental health boost, combining gentle movement, mindful breathing, and relaxation.",
    "Establish a bedtime routine to improve the quality of your sleep.",
    "Release tension by shaking out your limbs and taking a few deep breaths.",
    "Limit your exposure to negative news and social media.",
    "Spend 15 minutes in quiet reflection or meditation.",
    "Take time to pamper yourself with a relaxing bath.",
    "Take time to pamper yourself with a self-care activity",
    "Practice mindful breathing by focusing on your breath. Inhaling, holding and exhaling deeply your breath for a count of four",
    "Connect with nature by focusing on the sensation of wind or sunlight on your skin.",
    "Explore nature by taking a leisurely stroll in a park or natural setting.",
    "Enjoy a moment of silence.",
    "Create a Vision Board, visualize your goals."
  ]

  BREAK_TIME = [
    "Stand up, stretch your arms, and do a quick walk around to refresh your body and mind.",
    "Grab a glass of water and take a moment to hydrate for a refreshing break.",
    "Take a break to grab a snack",
    "Perform simple stretches to release tension in your neck, shoulders, and back.",
    "Step outside for a few minutes to soak in some natural sunlight for a mood boost.",
    "Take a creative break by doodling or sketching for a few minutes.",
    "Step outside and take a few deep breaths of fresh air to rejuvenate.",
    "Listen to a favorite song or calming music you like.",
    "Organize your workspace for a tidier and more focused work environment.",
    "Take a break from screens and engage in a tech-free activity for a short period.",
    "Watch a funny video on tiktok, watch a brief video of a comedian you like to bring laughter into your break time.",
    "Solve a quick puzzle, crosswords or sudoku to stimulate your mind during the break.",
    "Take a break from screens and immerse yourself in a short, engaging article or book for a mental escape",
    "Step outside and spend a few moments observing the world around you. Take note of the colors, sounds, and movements in nature or the urban environment, providing a brief mental escape.",
    "Take a break to discover new music. Listen to a song or artist you haven't heard before, and let yourself enjoy the experience without any specific goal."
  ]

  # 13 fitness
  FITNESS = [
    "Head outdoors, take a little walking or jog to boost cardiovascular health.",
    "Incorporate bodyweight exercises like squats, push-ups, and planks for strength training.",
    "Practice yoga for a combination of flexibility, balance, and mental relaxation.",
    "Perform short bursts of intense exercises followed by brief rest periods.",
    "Incorporate jump rope exercises for effective cardiovascular workout.",
    "Join a dance fitness class or follow dance workout videos.",
    "Rotate through different exercises in a circuit format and work on various muscle groups",
    "Create a playlist of your favorite dance tunes and engage in a dance fitness session at home.",
    "Connect with friends or family virtually and engage in a group workout session.",
    "Follow an Pilates routine, use online videos or apps for guidance.",
    "Let's do some core workout today",
    "Take a scenic walk outdoors, exploring different routes to keep things interesting.",
    "Create a cardio circuit at home by combining exercises like jumping jacks, high knees, burpees, and mountain climbers.",
  ]

  # 16 study
  STUDY = [
    "Take a look at POWER BI",
    "Acquire expertise in cloud computing platforms like AWS (Amazon Web Services), Azure, or Google Cloud.",
    "Acquire skills in mobile app development. Frameworks like React Native or Flutter can be valuable for cross-platform development.",
    "Familiarize yourself with DevOps principles and tools. Such as Jenkins, Docker, and Kubernetes.",
    "Cybersecurity fundamentals, such as understanding encryption, authentication, and best practices for securing applications.",
    "Learn about database systems, relational databases (e.g., MySQL, PostgreSQL).",
    "Learn about database systems, NoSQL databases (e.g., MongoDB)",
    "Work at your LinkedIn and improve it's design, update any new experiences",
    "Movie time for today - Insert Coin (2020) documentary",
    "Movie time for today - The Great Hack (2019) documentary",
    "Movie time for today - The Social Network (2010)",
    "Movie time for today - Codegirl (2015) documentary",
    "Movie time for today - Print the Legend (2014) documentary",
    "Movie time for today - Sunspring (2016) short film",
    "Machine Learning and AI, familiarize yourself with the basics of machine learning such as TensorFlow or PyTorch.",
    "Learn about AI concepts, including natural language processing (NLP), computer vision, and reinforcement learning.",
  ]
end
